### ISSUE TITLE
Issue with alkesh26 commits shown against alkeshghorpade

### ISSUE THREAD

**Issue by alkesh26** [rails/rails-contributors#173]
I am contributing to Rails since 2019 and it is mapped to [alkesh26](https://contributors.rubyonrails.org/contributors/alkesh26/commits) (16 commits).

But my recent two commits are mapped to [alkeshghorpade](https://contributors.rubyonrails.org/contributors/alkeshghorpade/commits).

I have not changed my GitHub handle https://github.com/alkesh26 and all my 18 Rails commits are visible [here](https://github.com/rails/rails/pulls?q=is%3Apr+author%3Aalkesh26+is%3Aclosed) including the recent ones.

What I remember is I deleted the forked Rails repo under `alkesh26` and forked it again. Not sure if this can be the cause.

**Comment by alkesh26** [comment]
I will try fixing this issue and raise a PR if possible.

**Comment by fxn** [comment]
Hi!

```
commit 40770b6878df64b0c92db877884fa361c9689b43
Author: alkeshghorpade <alkesh26@gmail.com>
Date:   Wed Mar 10 10:57:53 2021 +0530

    corrected the output of maximum in ActiveSupport changelog
```

Yes, that is because the app does not know `alkeshghorpade` is you.

Could you please add a mapping in [this file](https://github.com/rails/rails-contributors/blob/master/app/models/names_manager/canonical_names.rb)? Look for the series of `map` calls, and insert yours ordered:

```ruby
map 'alkesh26`, `alkeshghorpade`
```

Also, if you'd prefer to have your real name associated to both handles, you can also do that:

```ruby
map 'My Real Name`, 'alkesh26`, `alkeshghorpade`
```

The one you want to appear on the website is the leftmost argument.

That file has test coverage too.

**Comment by alkesh26** [comment]
Hey @fxn thanks for the update, I was going through the same file which you pointed out above. I will add the above changes and raise a PR.
